name: CI
on:
    push:
        paths:
            - "assets/**"
            - "src/**"
            - "tests/**"
            - "dev/**"
            - ".github/workflows/*"
            - "lock.json"
    workflow_dispatch:
env:
    denoVersion: "v1.20.5"
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Clone repository
                uses: actions/checkout@v3
                with:
                    submodules: false
                    persist-credentials: false

            -   name: Setup Deno
                uses: denoland/setup-deno@main
                with:
                    deno-version: "${{ env.denoVersion }}"

            -   name: Format
                run: deno task fmt:check

            -   name: Lint
                run: deno task lint

    test:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   name: Clone repository
                uses: actions/checkout@v3
                with:
                    submodules: true
                    persist-credentials: false

            -   name: Setup Deno
                uses: denoland/setup-deno@main
                with:
                    deno-version: "${{ env.denoVersion }}"

            -   name: Cache dependencies
                uses: actions/cache@v3
                env:
                    cache-name: cache-deno
                with:
                    # deno cache files are stored in `~/.cache/deno` on Linux/macOS
                    path: ~/.cache/deno
                    key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-build-${{ env.cache-name }}-
                        ${{ runner.os }}-build-
                        ${{ runner.os }}-

            -   name: Run tests
                run: deno task test:coverage -- `find src/ -name '*.ts' | xargs echo` tests/

            -   name: Generate lcov
                run: deno task coverage

            -   name: Upload coverage
                uses: codecov/codecov-action@v3
                with:
                    files: out/coverage.lcov
                    token: ${{ secrets.CODECOV_TOKEN }}
                    fail_ci_if_error: true
                    verbose: true

# TODO bundle jobs
