name: CI
on:
    push:
        paths:
            - "assets/**"
            - "src/**"
            - "tests/**"
            - "dev/**"
            - ".github/workflows/*"
            - "lock.json"
    workflow_dispatch:
env:
    denoVersion: "v1.20.6"
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Setup
                uses: dhardtke/prandium/.github/actions/setup@main
                with:
                    denoVersion: ${{ env.denoVersion }}

            -   name: Format
                run: deno task fmt:check

            -   name: Lint
                run: deno task lint

    test:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   name: Setup
                uses: dhardtke/prandium/.github/actions/setup@main
                with:
                    denoVersion: ${{ env.denoVersion }}

            -   name: Run tests
                run: deno task test:coverage -- `find src/ -name '*.ts' | xargs echo` tests/

            -   name: Generate lcov
                run: deno task coverage

            -   name: Upload coverage
                uses: codecov/codecov-action@v3
                with:
                    files: out/coverage.lcov
                    token: ${{ secrets.CODECOV_TOKEN }}
                    fail_ci_if_error: true
                    verbose: true

    build:
        needs: [ lint, test ]
        runs-on: ubuntu-latest
        steps:
            -   name: Setup
                uses: dhardtke/prandium/.github/actions/setup@main
                with:
                    denoVersion: ${{ env.denoVersion }}

            -   name: Build
                run: deno task build
