name: CI
on:
    push:
        paths:
            - "assets/**"
            - "src/**"
            - "tests/**"
            - "dev/**"
env:
    denoVersion: "v1.8.1"
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Clone repository
                uses: actions/checkout@v2
                with:
                    submodules: false
                    persist-credentials: false

            -   name: Setup Deno
                uses: denolib/setup-deno@v2
                with:
                    deno-version: ${{ env.denoVersion }}

            -   name: Format
                run: deno fmt --check src tests dev

            -   name: Lint
                run: deno lint --unstable src tests dev

    test:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   name: Clone repository
                uses: actions/checkout@v2
                with:
                    submodules: true
                    persist-credentials: false

            -   name: Setup Deno
                uses: denolib/setup-deno@v2
                with:
                    deno-version: ${{ env.denoVersion }}

            -   name: Run tests
                run: deno test --coverage=./cov --unstable --allow-all

        #            -   name: Generate lcov
        #                if: matrix.deno == "canary"
        #                run: deno coverage --unstable --lcov ./cov > cov.lcov

# TODO bundle jobs
