name: learn-github-actions
on: [ push ]
jobs:
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: denolib/setup-deno@v2
                with:
                    deno-version: v1.8.1
            -   run: |
                    deno --version
                    deno run https://deno.land/std/examples/welcome.ts
                    deno install --allow-read -n deno_cat https://deno.land/std/examples/cat.ts
                    deno_cat ./README.md
